#!/bin/sh

uci set gargoyle.display.connection_ap_management="AP Management"
uci set gargoyle.scripts.connection_ap_management="ap_management.sh"
uci set gargoyle.connection.ap_management="700"

uci commit
