#!/bin/sh
uciDefaultsContainerVar="$1"
if [ -z "$uciDefaultsContainerVar" ]; then
	uciDefaultsContainerVar="uciDefaults"
fi
cat <<EOF
$uciDefaultsContainerVar = {
	'wireless': {
		'wifi-device': {
			'disabled': '0',
			'channel': 'auto',
			'chanbw': '20',
			'diversity': '1',
			'beacon_int': '100',
			'legacy_rates': '1',
			'cell_density': '0',
			'log_level': '2',
			'no_scan': '0',
			'ht_coex': '0',
			'antenna_gain': '0',
			'frameburst': '0',
			'ldpc': '1',
			'greenfield': '0',
			'short_gi_20': '1',
			'short_gi_40': '1',
			'tx_stbc': '1',
			'rx_stbc': '3',
			'max_amsdu': '1',
			'dsss_cck_40': '1',
			'rxldpc': '1',
			'short_gi_80': '1',
			'short_gi_160': '1',
			'tx_stbc_2by1': '1',
			'su_beamformer': '1',
			'su_beamformee': '1',
			'mu_beamformer': '1',
			'mu_beamformee': '1',
			'vht_txop_ps': '1',
			'htc_vht': '1',
			'rx_antenna_pattern': '1',
			'tx_antenna_pattern': '1',
			'vht_max_a_mpdu_len_exp': '7',
			'vht_max_mpdu': '11454',
			'vht_link_adapt': '3',
			'vht160': '2'
		},
		'wifi-iface': {
			'network': 'lan',
			'mode': 'ap',
			'disabled': '0',
			'ssid': 'OpenWrt',
			'hidden': '0',
			'isolate': '0',
			'doth': '0',
			'wmm': '1',
			'encryption': 'none',
			'macfilter': 'disable',
			'rsn_preauth': '0',
			'ieee80211w': '0',
			'dtim_period': '0',
			'short_preamble': '1',
			'max_listen_int': '65535',
			'wds': '0',
			'sae_pwe': '0',
			'start_disabled': '0',
			'default_disabled': '0',
			'port': '1812',
			'wpa_group_rekey': '600',
			'auth_port': '1812',
			'auth_cache': '0',
			'acct_port': '1813',
			'dae_port': '3799',
			'dynamic_vlan': '0',
			'vlan_naming': '1',
			'auth': 'MSCHAPV2',
			'wpa_disable_eapol_key_retries': '0',
			'tdls_prohibit': '0',
			'wps_device_name': 'LEDE AP',
			'wps_device_type': '6-0050F204-1',
			'wps_label': '0',
			'wps_manufacturer': 'lede-project.org',
			'wps_pushbutton': '0',
			'ieee80211k': '0',
			'rrm_neighbor_report': '0',
			'rrm_beacon_report' : '0',
			'ieee802v': '0',
			'time_advertisement': '0',
			'wmm_sleep_mode': '0',
			'bss_transition': '0',
			'ieee80211r': '0',
			'mobility_domain': '4f57',
			'r0_key_lifetime': '10000',
			'r1_key_holder': '00004f577274',
			'reassociation_deadline': '1000',
			'r0kh': 'ff:ff:ff:ff:ff:ff,*,\$key',
			'r1kh': '00:00:00:00:00:00,00:00:00:00:00:00,\$key',
			'pmk_r1_push': '0',
			'ft_over_ds': '1',
			'ft_psk_generate_local': '0',
			'disassoc_low_ack': '1',
			'max_inactivity': '300',
			'skip_inactivity_poll': '0',
			'max_listen_interval': '65535'
		}
	}
};
EOF